# Generated by Django 3.2.9 on 2021-12-01 15:09

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='booking_state',
            field=models.CharField(choices=[('PENDING', 'pending'), ('AVAILABLE', 'available'), ('UNAVAILABLE', 'unavailable')], default=main.models.BookingStateEnum['PENDING'], max_length=20),
        ),
    ]
