# Generated by Django 3.2.9 on 2021-12-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_book_booking_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCreate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=200)),
                ('student_number', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='booking_state',
        ),
        migrations.AlterField(
            model_name='book',
            name='bookcode',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
