# Generated by Django 3.2.9 on 2021-12-07 15:10

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211207_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='booking_state',
            field=models.CharField(choices=[('PENDING', 'pending'), ('AVAILABLE', 'available'), ('UNAVAILABLE', 'unavailable')], default=main.models.BookingStateEnum['PENDING'], max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookcode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(default=0, max_length=20, verbose_name=main.models.Category),
        ),
    ]
