# Generated by Django 3.2.9 on 2021-11-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211109_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bookname', models.CharField(blank=True, max_length=30)),
                ('category', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
