# Generated by Django 3.2.9 on 2021-11-09 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_book_bookcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='bookcode',
        ),
    ]
