# Generated by Django 3.2.9 on 2021-11-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_book_bookcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookcode',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
